### ISSUE TITLE
Use controller-runtime API to figure container ID in onload-cplane-ds

### ISSUE THREAD

**Issue by ivatet-amd** [Xilinx-CNS/kubernetes-onload#15]
The Onload control plane pods, created with `onload-cplane-ds`, use cgroup V1 slice names to figure out its container ID, which is not a supported way of achieving this.

Instead, the pods should use the controller-runtime API (https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client) to query Kubernetes API servers from within the pod.

(The control plane later passes the container ID to the Onload kernel module along with a path to the `crictl`, so the module launches new control plane instances with `crictl`.)

Also, tracked as ON-14911.

**Comment by tcrawley-xilinx** [comment]
Done on master with commit [b010da4dab5f52f3bbf3f83631631d7b014dad2a](https://github.com/Xilinx-CNS/kubernetes-onload/commit/b010da4dab5f52f3bbf3f83631631d7b014dad2a)
